# Create a Docker image for the Local Neighborhood algorithm here

# Local Neighborhood wrapper
# https://github.com/livj4711/spras
FROM python:3.10-alpine

WORKDIR /LocalNeighborhood
COPY local_neighborhood.py .
